import type { Metadata } from "next";
import { Albert_Sans, Poppins, Sora } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  style: ["italic", "normal"],
  variable: "--font-poppins",
});

const albertSans = Albert_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-albertsans",
});

const sora = Sora({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${poppins.variable} ${albertSans.variable} ${sora.variable} } h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}
        <div>
          <Toaster position="top-right" reverseOrder={false} />
        </div>
      </body>
    </html>
  );
}
